services:
  - type: web
    name: dehla-pakad
    runtime: node
    plan: free
    buildCommand: cd client && npm install --include=dev && npm run build && cd ../server && npm install --include=dev && npm run build
    startCommand: cd server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
