services:
  - type: web
    name: dehla-pakad
    runtime: node
    plan: free
    buildCommand: cd server && npm install --include=dev && npm run build
    startCommand: cd server && node dist/server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
